<?php
// Мобильное меню: разделы каталога аккордеоном (DEPTH_LEVEL 2 — подпункты), затем страницы
$sub = ['DEPTH_LEVEL' => 2];
$aMenuLinks = [
    ['Чай', '/magazin/chay/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Чёрный чай', '/magazin/chay/chernyy-chay/', [], $sub, ''],
    ['Зелёный чай', '/magazin/chay/zelenyy-chay/', [], $sub, ''],
    ['Улуны', '/magazin/chay/uluny/', [], $sub, ''],
    ['Травяной чай', '/magazin/chay/travyanoy-chay/', [], $sub, ''],
    ['Пуэр', '/magazin/chay/puer/', [], $sub, ''],
    ['Матча', '/magazin/chay/matcha/', [], $sub, ''],
    ['Фруктовый чай', '/magazin/chay/fruktovyy-chay/', [], $sub, ''],
    ['Красный чай', '/magazin/chay/krasnyy-chay/', [], $sub, ''],
    ['Добавки к чаю', '/magazin/chay/dobavki-k-chayu/', [], $sub, ''],
    ['Кофе', '/magazin/kofe/', [], ['DEPTH_LEVEL' => 1], ''],
    ['BOTANICA кофе под эспрессо', '/magazin/kofe/dlya-espresso/', [], $sub, ''],
    ['BOTANICA фильтр-кофе', '/magazin/kofe/filtr-kofe/', [], $sub, ''],
    ['Кофемашины Jetinno', '/magazin/professionalnye-kofemashiny/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Аренда кофемашин', '/arenda-kofemashin/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Для офиса', '/arenda-kofemashin/', [], $sub, ''],
    ['Для кафе и HoReCa', '/arenda-kofemashin/', [], $sub, ''],
    ['На мероприятие', '/arenda-kofemashin/#event', [], $sub, ''],
    ['Аксессуары', '/magazin/aksessuary/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Заварочные чайники', '/magazin/zavarnye-chayniki/', [], $sub, ''],
    ['Воронки для фильтр-кофе', '/magazin/voronki/', [], $sub, ''],
    ['Чайная посуда', '/magazin/chaynaya-posuda/', [], $sub, ''],
    ['Кофе по подписке', '/podpiska/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Услуги и сервис', '/servis/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Ремонт кофемашин', '/servis/remont-kofemashin/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Журнал', '/news/', [], ['DEPTH_LEVEL' => 1], ''],
    ['О компании', '/o-kompanii/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Оплата и доставка', '/oplata-i-dostavka/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Контакты', '/kontakty/', [], ['DEPTH_LEVEL' => 1], ''],
    ['Личный кабинет', '/personal/', [], ['DEPTH_LEVEL' => 1], ''],
];
